serenity.project.name = Serenity BDD QA Innovation Lab Mobile
serenity.take.screenshots = AFTER_EACH_STEP
webdriver.driver = appium

appium.hub = http://localhost:4723/

#Android capabilities
appium.platformName = Android
appium.deviceName = Android Emulator
appium.automationName = UIAutomator2
appium.app = C:/Users/ariel.morales/Documents/GitHub/Mobile/src/test/resources/app/mda-2.0.2-23.apk
appium.package = com.saucelabs.mydemoapp.android
appium.appActivity = com.saucelabs.mydemoapp.android.view.activities.SplashActivity

